In [1]:
import torch
import torch.nn as nn

In [68]:
def lstm(bi, inpu_dim):
    inp_size, hidden_size, num_layers = inpu_dim, 1, 1
    return nn.LSTM(inp_size, hidden_size, num_layers, bidirectional=bi)
    

def printer(inpt, o, h):
    # [seq len, batch size, inp dimension]
    print('Input: \n')
    print(inpt)
    # [seq len, batch size, inp dimension * 2]
    print('Output: \n')
    print(o)
    # [num_layers * 2 , batch size, inp dimension]
    print('Hidden: \n')
    print(h)

In [69]:
inpt = torch.randn([4])
inpt = inpt.view(2, 2, 1)
model = lstm(False, inpu_dim = 1)

for name, param in model.named_parameters():
    param.data.fill_(1)
    
h = None

for t in inpt:
    if h == None:
        o, (h, c) = model(t.unsqueeze(0))
    else:
        o, (h, c) = model(t.unsqueeze(0), (h, c))
    printer(t, o, h)
    print('---------------------------------------')
    
model = lstm(False, inpu_dim = 1)

for name, param in model.named_parameters():
    param.data.fill_(1)

o, (h, c) = model(inpt)
printer(t, o, h)

Input: 

tensor([[ 0.9684],
        [-1.3935]])
Output: 

tensor([[[0.7019],
         [0.2180]]], grad_fn=<StackBackward>)
Hidden: 

tensor([[[0.7019],
         [0.2180]]], grad_fn=<StackBackward>)
---------------------------------------
Input: 

tensor([[-0.0419],
        [-0.2666]])
Output: 

tensor([[[0.8859],
         [0.7154]]], grad_fn=<StackBackward>)
Hidden: 

tensor([[[0.8859],
         [0.7154]]], grad_fn=<StackBackward>)
---------------------------------------
Input: 

tensor([[-0.0419],
        [-0.2666]])
Output: 

tensor([[[0.7019],
         [0.2180]],

        [[0.8859],
         [0.7154]]], grad_fn=<StackBackward>)
Hidden: 

tensor([[[0.8859],
         [0.7154]]], grad_fn=<StackBackward>)


In [74]:
inpt = torch.randn([4])
inpt = inpt.view(4, 1, 1) # Shape (inpt): [seq len, batch size, inp dimension]
print(inpt)
print("------------------------")

model = lstm(False, inpu_dim = 1)
for name, param in model.named_parameters():
    param.data.fill_(1)
h = None

inpx = torch.flip(inpt, [0, 1])


for t, tx in zip(inpt, inpx):
    if h == None:
        o, (h, c) = model(t.unsqueeze(0))
        ox, (hx, cx) = model(tx.unsqueeze(0))
    else:
        o, (h, c) = model(t.unsqueeze(0), (h, c))
        ox, (hx, cx) = model(tx.unsqueeze(0), (hx, cx))
    printer(t, o, h)
    print('--- Reverse')
    printer(tx, ox, hx)
    print("------------------------")
    
    
    
model = lstm(True, inpu_dim = 1)
for name, param in model.named_parameters():
    param.data.fill_(1)

o, (h, c) = model(inpt)
printer(t, o, h)

tensor([[[-1.1009]],

        [[ 1.6539]],

        [[-0.5385]],

        [[-1.9041]]])
------------------------
Input: 

tensor([[-1.1009]])
Output: 

tensor([[[0.3334]]], grad_fn=<StackBackward>)
Hidden: 

tensor([[[0.3334]]], grad_fn=<StackBackward>)
--- Reverse
Input: 

tensor([[-1.9041]])
Output: 

tensor([[[0.0262]]], grad_fn=<StackBackward>)
Hidden: 

tensor([[[0.0262]]], grad_fn=<StackBackward>)
------------------------
Input: 

tensor([[1.6539]])
Output: 

tensor([[[0.8852]]], grad_fn=<StackBackward>)
Hidden: 

tensor([[[0.8852]]], grad_fn=<StackBackward>)
--- Reverse
Input: 

tensor([[-0.5385]])
Output: 

tensor([[[0.5312]]], grad_fn=<StackBackward>)
Hidden: 

tensor([[[0.5312]]], grad_fn=<StackBackward>)
------------------------
Input: 

tensor([[-0.5385]])
Output: 

tensor([[[0.8925]]], grad_fn=<StackBackward>)
Hidden: 

tensor([[[0.8925]]], grad_fn=<StackBackward>)
--- Reverse
Input: 

tensor([[1.6539]])
Output: 

tensor([[[0.9273]]], grad_fn=<StackBackward>)
Hidden: 

ten

In [5]:
for name, param in lstm(False, inpu_size = 1).named_parameters():
    print(name)

weight_ih_l0
weight_hh_l0
bias_ih_l0
bias_hh_l0


In [6]:
for name, param in lstm(True, inpu_size = 1).named_parameters():
    print(name)

weight_ih_l0
weight_hh_l0
bias_ih_l0
bias_hh_l0
weight_ih_l0_reverse
weight_hh_l0_reverse
bias_ih_l0_reverse
bias_hh_l0_reverse


Basically, output of LSTM is the cummulative hidden states over all time steps.
While hidden state is over t time Step.
for Bi-directional, we get forward and backward both in output.
We can concatenate it or sum or multiply its just another hyper parameter and then pass it to linear layer to finally predict!